### ISSUE TITLE
GARPFRM package

### ISSUE THREAD

**Issue by arturochian** [rossb34/PerformanceMeasures#1]
This is the R package (from r-forge) you installed? I have some problem related installing.

https://r-forge.r-project.org/R/?group_id=1791

PD: Nice shiny

**Comment by rossb34** [comment]
The build on R-Forge is fixed, you should be able to install now.

Ross

**Comment by arturochian** [comment]
Working! are you the maintainer of this R package? It seems very interesting package. I could help in order to improve it (I'm going to take the FRM I on May of this year).

**Comment by rossb34** [comment]
I'm not the listed maintainer, but I have been doing most of the
development work. I'm glad you are interested in the package. We don't have
plans yet for contributors, but I'll keep you in mind as we discuss
development plans. Any feedback you can provide as well as bug reports and
patches is always useful.

Thanks,
Ross
